os: Visual Studio 2017

# version format
version: 1.3.{build}

cache:
  - src\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  
build:
  project: ImageProcessor.Plugins.Pdf.csproj
  
before_build:
  - nuget restore

artifacts:
  - path: '**\*.nupkg' # find all NuGet packages recursively
    name: MyApp

deploy:
  provider: NuGet
  api_key:
    secure: hd63fmfN87wpPr16CMeB3I4jj/+mj0oHJxUIaQb7t61spQKNJfwxmfp059BKs6DX
  skip_symbols: false
  artifact: MyApp

dotnet_csproj:
  patch: true
  file: '*.csproj'
  version: '{version}'
  package_version: '{version}'
  
configuration:
  - Release
